version: '3'

services:
  vpn:
    build:
        context: ./image
        dockerfile: Dockerfile
    restart: always
    env_file:
      - ./docker-compose.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
